import {createClient, type RawQueryResponse} from '@sanity/client'
import {describe, expectTypeOf, test} from 'vitest'

type FooResult = {
  bar: number
}

// This would normally be generated by @sanity/codegen
declare module '@sanity/client' {
  export interface SanityQueries {
    "*[_type == 'foo']": FooResult
  }
}

describe('client.fetch', () => {
  const client = createClient({})

  describe('without params', () => {
    test('known query type', async () => {
      const resp = await client.fetch("*[_type == 'foo']")
      expectTypeOf(resp).toExtend<FooResult>()
    })

    test('ad-hoc query type', async () => {
      const resp = await client.fetch("*[_type == 'bar']")
      expectTypeOf(resp).toExtend<any>()
    })

    test('ad-hoc query with a custom type', async () => {
      type Result = {bar: string}
      const resp = await client.fetch<Result>("*[_type == 'bar']")
      expectTypeOf(resp).toExtend<Result>()
    })

    test('known query type, but overriden with ad-hoc type', async () => {
      type Result = {bar: string}
      const resp = await client.fetch<Result>("*[_type == 'foo']")
      expectTypeOf(resp).toExtend<Result>()
    })
  })

  describe('unfiltered response', () => {
    test('known query type', async () => {
      const resp = await client.fetch("*[_type == 'foo']", {}, {filterResponse: false})
      expectTypeOf(resp).toExtend<RawQueryResponse<FooResult>>()
    })

    test('ad-hoc query type', async () => {
      const resp = await client.fetch("*[_type == 'bar']", {}, {filterResponse: false})
      expectTypeOf(resp).toExtend<RawQueryResponse<any>>()
    })

    test('ad-hoc query with a custom type', async () => {
      type Result = {bar: string}
      const resp = await client.fetch<Result>("*[_type == 'bar']", {}, {filterResponse: false})
      expectTypeOf(resp).toExtend<RawQueryResponse<Result>>()
    })

    test('known query type, but overriden with ad-hoc type', async () => {
      type Result = {bar: string}
      const resp = await client.fetch<Result>("*[_type == 'foo']", {}, {filterResponse: false})
      expectTypeOf(resp).toExtend<RawQueryResponse<Result>>()
    })
  })
})
