import {createClient, type RawQueryResponse} from '@sanity/client'
import {
  type ClientReturnStega,
  stegaBrand,
  type StegaBranded,
  stegaClean,
  type StegaCleaned,
  type StegaString,
} from '@sanity/client/stega'
import {describe, expectTypeOf, test} from 'vitest'

type ImageLocation = 'left' | 'right'

interface PostQueryResult {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  title: string
  imageLocation: ImageLocation
  slug: {_type: 'slug'; current: string}
  publishedAt: string | null
  tags: string[]
}

// This would normally be generated by @sanity/codegen
declare module '@sanity/client' {
  export interface SanityQueries {
    "*[_type == 'stegaPost'][0]": PostQueryResult
  }
}

describe('StegaString', () => {
  test('comparing against a string literal is a type error', () => {
    const branded = stegaBrand({imageLocation: 'left' as ImageLocation}).imageLocation
    // @ts-expect-error -- TS2367: This comparison appears to be unintentional
    if (branded === 'left') {
      // noop
    }
    // @ts-expect-error -- TS2367: This comparison appears to be unintentional
    if ('left' === branded) {
      // noop
    }
    // Comparing after cleaning is allowed
    if (stegaClean(branded) === 'left') {
      // noop
    }
  })

  test('wide strings are also unsafe to compare against literals', () => {
    const branded = stegaBrand({title: 'foo'}).title
    // @ts-expect-error -- TS2367: This comparison appears to be unintentional
    if (branded === 'foo') {
      // noop
    }
    if (stegaClean(branded) === 'foo') {
      // noop
    }
  })

  test('switch cases on branded strings are a type error', () => {
    const branded = stegaBrand({imageLocation: 'left' as ImageLocation}).imageLocation
    switch (branded) {
      // @ts-expect-error -- TS2678: not comparable
      case 'left':
        break
      // @ts-expect-error -- TS2678: not comparable
      case 'right':
        break
    }
    switch (stegaClean(branded)) {
      case 'left':
        break
      case 'right':
        break
      // @ts-expect-error -- TS2678: not part of the union after cleaning
      case 'center':
        break
    }
  })

  test('assigning to a literal union is a type error', () => {
    const branded = stegaBrand({imageLocation: 'left' as ImageLocation}).imageLocation
    function takesUnion(value: 'left' | 'right') {
      return value
    }
    // @ts-expect-error -- not assignable to 'left' | 'right'
    takesUnion(branded)
    takesUnion(stegaClean(branded))
  })

  test('still assignable to string, and string operations keep working', () => {
    const branded = stegaBrand({title: 'foo'}).title
    expectTypeOf(branded).toMatchTypeOf<string>()
    expectTypeOf(branded.toUpperCase()).toMatchTypeOf<string>()
    expectTypeOf(branded.length).toMatchTypeOf<number>()
    expectTypeOf(`/${branded}`).toMatchTypeOf<string>()
    // Comparing against a non-literal string is allowed
    const anyString = 'foo' as string
    if (branded === anyString) {
      // noop
    }
  })

  test('comparing to plain string literals is allowed for unbranded strings (control case)', () => {
    const plain = {imageLocation: 'left' as ImageLocation}.imageLocation
    if (plain === 'left') {
      // noop
    }
  })
})

describe('StegaBranded', () => {
  test('brands strings and leaves other primitives alone', () => {
    const branded = stegaBrand({title: 'foo', rating: 4, isDraft: false, missing: null})
    expectTypeOf(branded.title).toEqualTypeOf<StegaString<string>>()
    expectTypeOf(branded.rating).toEqualTypeOf<number>()
    expectTypeOf(branded.isDraft).toEqualTypeOf<boolean>()
    expectTypeOf(branded.missing).toEqualTypeOf<null>()
  })

  test('underscore prefixed keys keep their plain string type', () => {
    const branded = stegaBrand({
      _id: 'id',
      _type: 'post' as const,
      _createdAt: '2026-01-01',
      _updatedAt: '2026-01-01',
      _rev: 'rev',
      _key: 'key',
      _ref: 'ref',
    })
    expectTypeOf(branded._id).toEqualTypeOf<string>()
    expectTypeOf(branded._type).toEqualTypeOf<'post'>()
    expectTypeOf(branded._createdAt).toEqualTypeOf<string>()
    expectTypeOf(branded._updatedAt).toEqualTypeOf<string>()
    expectTypeOf(branded._rev).toEqualTypeOf<string>()
    expectTypeOf(branded._key).toEqualTypeOf<string>()
    expectTypeOf(branded._ref).toEqualTypeOf<string>()
  })

  test('discriminated union narrowing on _type keeps working', () => {
    type Section = {_type: 'hero'; headline: string} | {_type: 'gallery'; images: {alt: string}[]}
    const section = stegaBrand({} as Section)
    if (section._type === 'hero') {
      expectTypeOf(section.headline).toEqualTypeOf<StegaString<string>>()
    } else {
      expectTypeOf(section._type).toEqualTypeOf<'gallery'>()
      expectTypeOf(section.images[0].alt).toEqualTypeOf<StegaString<string>>()
    }
  })

  test('slug.current keeps its plain string type', () => {
    const branded = stegaBrand({
      slug: {_type: 'slug' as const, current: 'foo'},
      nested: {slug: {current: 'foo'}},
    })
    expectTypeOf(branded.slug.current).toEqualTypeOf<string>()
    expectTypeOf(branded.nested.slug.current).toEqualTypeOf<string>()
  })

  test('string valued slug keys keep their plain string type', () => {
    // Covers `"slug": slug.current` projections
    const branded = stegaBrand({slug: 'foo'})
    expectTypeOf(branded.slug).toEqualTypeOf<string>()
  })

  test('current keys outside of slug objects are branded', () => {
    const branded = stegaBrand({pagination: {current: 'page-1'}})
    expectTypeOf(branded.pagination.current).toEqualTypeOf<StegaString<string>>()
  })

  test('nullable unions distribute', () => {
    const branded = stegaBrand({publishedAt: null as string | null})
    expectTypeOf(branded.publishedAt).toEqualTypeOf<StegaString<string> | null>()
  })

  test('optional properties stay optional', () => {
    const branded = stegaBrand({} as {title?: string})
    expectTypeOf(branded).toEqualTypeOf<{title?: StegaString<string>}>()
  })

  test('arrays and readonly arrays of strings are branded', () => {
    const branded = stegaBrand({tags: ['a'], categories: ['b'] as readonly string[]})
    expectTypeOf(branded.tags).toEqualTypeOf<StegaString<string>[]>()
    expectTypeOf(branded.categories).toEqualTypeOf<readonly StegaString<string>[]>()
  })

  test('Portable Text blocks only brand span text', () => {
    type SpanChild = {_type: 'span'; _key: string; text: string; marks: string[]}
    type InlineChild = {_type: 'stockTicker'; _key: string; symbol: string}
    type Block = {
      _type: 'block'
      _key: string
      style: 'normal' | 'h1'
      listItem?: 'bullet'
      markDefs: {_type: 'link'; _key: string; href: string}[]
      children: (SpanChild | InlineChild)[]
    }
    const block = stegaBrand({} as Block)
    // The stega encoder never visits these properties on blocks, see `walkMap`
    expectTypeOf(block.style).toEqualTypeOf<'normal' | 'h1'>()
    expectTypeOf(block.listItem).toEqualTypeOf<'bullet' | undefined>()
    expectTypeOf(block.markDefs).toEqualTypeOf<{_type: 'link'; _key: string; href: string}[]>()
    const child = block.children[0]
    if (child._type === 'span') {
      // Only the text of spans is encoded
      expectTypeOf(child.text).toEqualTypeOf<StegaString<string>>()
      expectTypeOf(child.marks).toEqualTypeOf<string[]>()
    } else {
      // Custom inline objects get the regular branding treatment
      expectTypeOf(child.symbol).toEqualTypeOf<StegaString<string>>()
    }
  })

  test('any, unknown and never pass through', () => {
    expectTypeOf<StegaBranded<any>>().toEqualTypeOf<any>()
    expectTypeOf<StegaBranded<unknown>>().toEqualTypeOf<unknown>()
    expectTypeOf<StegaBranded<never>>().toEqualTypeOf<never>()
  })

  test('branding is idempotent', () => {
    const once = stegaBrand({title: 'foo'})
    const twice = stegaBrand(once)
    expectTypeOf(twice).toEqualTypeOf(once)
  })

  test('handles large page builder shaped results', () => {
    type LargeResult = {
      _id: string
      _type: 'page'
      title: string
      seo: {title: string; description: string} | null
      sections: Array<
        | {_type: 'hero'; _key: string; headline: string; cta: {label: string; url: string}}
        | {_type: 'gallery'; _key: string; images: {alt: string; asset: {_ref: string}}[]}
        | {_type: 'quote'; _key: string; text: string; attribution: string | null}
        | {_type: 'features'; _key: string; items: {title: string; description: string}[]}
      >
    }
    const branded = stegaBrand({} as LargeResult)
    const section = branded.sections[0]
    if (section._type === 'hero') {
      expectTypeOf(section.headline).toEqualTypeOf<StegaString<string>>()
      expectTypeOf(section.cta.url).toEqualTypeOf<StegaString<string>>()
    }
    expectTypeOf(stegaClean(branded)).toEqualTypeOf<LargeResult>()
  })
})

describe('client.fetch with ClientReturnStega', () => {
  const client = createClient({})

  test('known query type is branded', async () => {
    const resp = await client.fetch<ClientReturnStega<"*[_type == 'stegaPost'][0]">>(
      "*[_type == 'stegaPost'][0]",
    )
    expectTypeOf(resp).toEqualTypeOf<StegaBranded<PostQueryResult>>()
    expectTypeOf(resp._id).toEqualTypeOf<string>()
    expectTypeOf(resp._type).toEqualTypeOf<'post'>()
    expectTypeOf(resp.slug.current).toEqualTypeOf<string>()
    expectTypeOf(resp.title).toEqualTypeOf<StegaString<string>>()
    // @ts-expect-error -- TS2367: must be cleaned before comparing
    if (resp.imageLocation === 'left') {
      // noop
    }
    if (stegaClean(resp.imageLocation) === 'left') {
      // noop
    }
  })

  test('drop-in for the typeof query pattern', async () => {
    const query = "*[_type == 'stegaPost'][0]"
    const resp = await client.fetch<ClientReturnStega<typeof query>>(query)
    expectTypeOf(resp).toEqualTypeOf<StegaBranded<PostQueryResult>>()
  })

  test('ad-hoc query type falls back to any', async () => {
    const resp = await client.fetch<ClientReturnStega<"*[_type == 'unknownQuery']">>(
      "*[_type == 'unknownQuery']",
    )
    expectTypeOf(resp).toEqualTypeOf<any>()
  })

  test('ad-hoc query with a custom fallback type', async () => {
    const resp = await client.fetch<ClientReturnStega<"*[_type == 'unknownQuery']", {bar: string}>>(
      "*[_type == 'unknownQuery']",
    )
    expectTypeOf(resp).toEqualTypeOf<StegaBranded<{bar: string}>>()
    expectTypeOf(resp.bar).toEqualTypeOf<StegaString<string>>()
  })

  test('unfiltered responses brand the result', async () => {
    const resp = await client.fetch<ClientReturnStega<"*[_type == 'stegaPost'][0]">>(
      "*[_type == 'stegaPost'][0]",
      {},
      {filterResponse: false},
    )
    expectTypeOf(resp).toMatchTypeOf<RawQueryResponse<StegaBranded<PostQueryResult>>>()
    expectTypeOf(resp.result.title).toEqualTypeOf<StegaString<string>>()
  })
})

describe('stegaClean', () => {
  test('round-trips a branded result back to the original type', () => {
    const branded = stegaBrand({} as PostQueryResult)
    expectTypeOf(stegaClean(branded)).toEqualTypeOf<PostQueryResult>()
  })

  test('recovers literal unions from branded strings', () => {
    const branded = stegaBrand({} as {imageLocation: ImageLocation})
    expectTypeOf(stegaClean(branded.imageLocation)).toEqualTypeOf<ImageLocation>()
    expectTypeOf(stegaClean(branded).imageLocation).toEqualTypeOf<ImageLocation>()
  })

  test('is an identity for unbranded values', () => {
    expectTypeOf(stegaClean('foo' as string)).toEqualTypeOf<string>()
    expectTypeOf(stegaClean('foo' as const)).toEqualTypeOf<'foo'>()
    expectTypeOf(stegaClean(4)).toEqualTypeOf<number>()
    expectTypeOf(stegaClean(null)).toEqualTypeOf<null>()
    expectTypeOf(stegaClean(undefined)).toEqualTypeOf<undefined>()
    expectTypeOf(stegaClean({} as PostQueryResult)).toEqualTypeOf<PostQueryResult>()
    expectTypeOf(stegaClean([] as string[])).toEqualTypeOf<string[]>()
    expectTypeOf(stegaClean({} as {nested: {tags: string[]; when?: Date}})).toEqualTypeOf<{
      nested: {tags: string[]; when?: Date}
    }>()
    expectTypeOf(stegaClean({} as unknown)).toEqualTypeOf<unknown>()
    expectTypeOf(stegaClean({} as any)).toEqualTypeOf<any>()
  })

  test('StegaCleaned inverts StegaBranded', () => {
    expectTypeOf<StegaCleaned<StegaBranded<PostQueryResult>>>().toEqualTypeOf<PostQueryResult>()
    expectTypeOf<StegaCleaned<StegaString<'left' | 'right'>>>().toEqualTypeOf<'left' | 'right'>()
  })
})
